import Head from 'next/head'

import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Mainpage from '@/pages/mainpage'
import Signin from '@/pages/signin'
export default function Home() {

  return (
    <>
      <Head>
        <title>Exercise Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet" />
      </Head>
      {/* <Mainpage/> */}
      <Signin/>
      
    </>
  )
}
